### ISSUE TITLE
修改为torch.save(net.module(),那行后又出现新的问题

### ISSUE THREAD

**Issue by YanDongchao** [wusaifei/HWCC_image_classification#1]
Traceback (most recent call last):
  File "/data/work/python_project/HWCC_image_classification/src/train.py", line 216, in <module>
    main()
  File "/data/work/python_project/HWCC_image_classification/src/train.py", line 201, in main
    torch.save(net.module(), '%s/net_%03d.pth' % (args.outf, epoch + 1))
  File "/data/work/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'inputs'

**Comment by wusaifei** [comment]
@YanDongchao 你好，真的非常抱歉，`net.module()`这一部分多了（），删除就行了`net.module`
