### ISSUE TITLE
在华为云部署customize_service.py报错AttributeError: 'collections.OrderedDict' object has no attribute 'eval'

### ISSUE THREAD

**Issue by wxyhv** [wusaifei/HWCC_image_classification#2]
[2019-12-23 13:45:22 +0000] [20] [INFO] Worker exiting (pid: 20)
Namespace(model_name='serve', model_path='/home/mind/model/net_011.pth', pt_server_name='127.0.0.1', service_file='/home/mind/model/customize_service.py')
model_name: serve
model_path: /home/mind/model/net_011.pth
[2019-12-23 13:45:23 +0000] [17] [INFO] Shutting down: Master
[2019-12-23 13:45:23 +0000] [17] [INFO] Reason: Worker failed to boot.
[2019-12-23 13:46:48 +0000] [17] [INFO] Starting gunicorn 19.8.1
[2019-12-23 13:46:48 +0000] [17] [INFO] Listening at: http://0.0.0.0:8080 (17)
[2019-12-23 13:46:48 +0000] [17] [INFO] Using worker: sync
[2019-12-23 13:46:48 +0000] [20] [INFO] Booting worker with pid: 20
[2019-12-23 13:46:52 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
__import__(module)
File "/home/mind/app.py", line 144, in
model_service = class_defs[0](model_name, model_path)
File "/home/mind/model/customize_service.py", line 30, in __init__
self.model.eval()
AttributeError: 'collections.OrderedDict' object has no attribute 'eval'

**Comment by wusaifei** [comment]
@wxyhv 你好代码已经修正 你看一下Github上写的。save(model.module)

**Comment by wxyhv** [comment]
可以的。优秀的楼主！
