### ISSUE TITLE
在华为云部署模型时报错AttributeError: Can't get attribute 'MemoryEfficientSwish' on

### ISSUE THREAD

**Issue by ysmhyl** [wusaifei/HWCC_image_classification#3]
[2019-12-24 12:45:34 +0000] [17] [INFO] Starting gunicorn 19.8.1
[2019-12-24 12:45:34 +0000] [17] [INFO] Starting gunicorn 19.8.1
[2019-12-24 12:45:34 +0000] [17] [INFO] Listening at: http://0.0.0.0:8080 (17)
[2019-12-24 12:45:34 +0000] [17] [INFO] Using worker: sync
[2019-12-24 12:45:34 +0000] [20] [INFO] Booting worker with pid: 20
[2019-12-24 12:45:38 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
__import__(module)
File "/home/mind/app.py", line 144, in
model_service = class_defs[0](model_name, model_path)
File "/home/mind/model/customize_service.py", line 29, in __init__
self.model = torch.load(model_path, map_location=map_location)
File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 574, in _load
result = unpickler.load()
AttributeError: Can't get attribute 'MemoryEfficientSwish' on

**Comment by wusaifei** [comment]
@ysmhyl 你好会不会是模型超时了 比赛要求一个小时的预测时间。 你可以重新git一下代码，代码重新更新了一下

**Comment by ysmhyl** [comment]
ok，我尝试一下。非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "仵赛飞"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 晚上9:10
收件人: "wusaifei/HWCC_image_classification"<HWCC_image_classification@noreply.github.com&gt;; 
抄送: "侯云龙"<1210731400@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [wusaifei/HWCC_image_classification] 在华为云部署模型时报错AttributeError: Can&#39;t get attribute &#39;MemoryEfficientSwish&#39; on (#3)




@ysmhyl 你好会不会是模型超时了 比赛要求一个小时的预测时间。 你可以重新git一下代码，代码重新更新了一下

**Comment by wusaifei** [comment]
@ysmhyl 不客气哈

**Comment by stevewinger** [comment]
你好！我刚才提交也是你这个问题，请问你解决了吗？应该不是预测超时，我提交后不到四十分钟就出结果了。。。。

**Comment by Russell-Zeng** [comment]
非常感谢您的分享！ 
我在线上部署的时候也出现了一样的问题，问题是出在self.model = torch.load(model_path, map_location=map_location)，也是出现了AttributeError: Can't get attribute 'MemoryEfficientSwish' on，我的线上部署代码安照官方的示例代码重写的，在线下预测的时候没有问题。但是线上部署时，总会报这个错误，请问您有什么建议吗？

**Comment by ysmhyl** [comment]
> 你好！我刚才提交也是你这个问题，请问你解决了吗？应该不是预测超时，我提交后不到四十分钟就出结果了。。。。

目前还没解决，出结果是线上可以预测吗？我在线下预测是没问题，在云上预测有问题。

**Comment by ysmhyl** [comment]
> 非常感谢您的分享！
> 我在线上部署的时候也出现了一样的问题，问题是出在self.model = torch.load(model_path, map_location=map_location)，也是出现了AttributeError: Can't get attribute 'MemoryEfficientSwish' on，我的线上部署代码安照官方的示例代码重写的，在线下预测的时候没有问题。但是线上部署时，总会报这个错误，请问您有什么建议吗？

情况+1，据作者说应该是 预测超时，目前我还在更改

**Comment by Russell-Zeng** [comment]
问题的原因已经找到： 是由于EfficientNet中使用的Memory Efficient Swish激活函数在低版本的Efficientnet中兼容性不佳导致的模型载入问题。
解决方法：将config.json中EfficientNet的版本从0.4.0改为0.5.1，然后重新部署模型即可

**Comment by ysmhyl** [comment]
> 问题的原因已经找到： 是由于EfficientNet中使用的Memory Efficient Swish激活函数在低版本的Efficientnet中兼容性不佳导致的模型载入问题。
> 解决方法：将config.json中EfficientNet的版本从0.4.0改为0.5.1，然后重新部署模型即可
学到了，多谢多谢

**Comment by ysmhyl** [comment]
> 问题的原因已经找到： 是由于EfficientNet中使用的Memory Efficient Swish激活函数在低版本的Efficientnet中兼容性不佳导致的模型载入问题。
> 解决方法：将config.json中EfficientNet的版本从0.4.0改为0.5.1，然后重新部署模型即可



> 问题的原因已经找到： 是由于EfficientNet中使用的Memory Efficient Swish激活函数在低版本的Efficientnet中兼容性不佳导致的模型载入问题。
> 解决方法：将config.json中EfficientNet的版本从0.4.0改为0.5.1，然后重新部署模型即可

实测有效！赞

**Comment by stevewinger** [comment]
> 问题的原因已经找到： 是由于EfficientNet中使用的Memory Efficient Swish激活函数在低版本的Efficientnet中兼容性不佳导致的模型载入问题。
> 解决方法：将config.json中EfficientNet的版本从0.4.0改为0.5.1，然后重新部署模型即可

感谢大佬！
